# Generated by Django 6.1 on 2026-09-22 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('technical', 'Technical'), ('hr', 'HR'), ('custom', 'Custom'), ('mixed', 'Mixed')], default='technical', max_length=20)),
                ('custom_interview_type', models.CharField(blank=True, max_length=100, null=True)),
                ('target_role', models.CharField(default='Software Developer', max_length=100)),
                ('experience_level', models.CharField(choices=[('fresher', 'Fresher'), ('experienced', 'Experienced')], default='fresher', max_length=20)),
                ('experience_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('interrupted', 'Interrupted')], default='in_progress', max_length=20)),
                ('total_questions', models.PositiveIntegerField(default=30)),
                ('current_question', models.PositiveIntegerField(default=1)),
                ('attempted_questions', models.PositiveIntegerField(default=0)),
                ('readiness_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField()),
                ('category', models.CharField(blank=True, default='General', max_length=100)),
                ('question_text', models.TextField()),
                ('answer', models.TextField(blank=True, default='')),
                ('score', models.FloatField(default=0)),
                ('feedback', models.TextField(blank=True, default='')),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('improvements', models.JSONField(blank=True, default=list)),
                ('is_attempted', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview_prep.interviewsession')),
            ],
            options={
                'ordering': ['question_number'],
                'constraints': [models.UniqueConstraint(fields=('session', 'question_number'), name='unique_question_per_session')],
            },
        ),
    ]
